### ISSUE TITLE
esrocos_build_project + linkings.yml does not support the partition definition

### ISSUE THREAD

**Issue by haianos** [ESROCOS/tools#4]
Currently, the `linkings.yml`, which generates the `ORCHESTRATION_OPTIONS`, does not support the definition of the partitions, but it is hard-coded in the command script (line 47).
Instead, it could be something like a dictionary, having as key the name of the partition, as values the list libraries to link.
For example:
```
libs:
  - x86_partition: ["lib1.a", "lib2.a"]
  - another_partition: ["lib3.a"]
```

**Comment by Kynneb** [comment]
Please have a look at #9 

The linkings.yml is now supposed to look like that:

```
first_partition:
  - pathtosomelib
  - pathtosomeotherlib
second_partition:
  - pathtosomelib
  - pathtosomeotherlib
```

At the moment that is still WIP so the linkings.yml has to be handwritten at the moment.

**Comment by haianos** [comment]
That sounds OK to me.
Integrating with our tool, we can already manipulate the linkings.yml by adding the required dependencies (or creating a new file if not found).
